[package]
name = "first-rust-project"
version = "0.1.0"
authors = ["yenkhoon.tan <tankhoon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"

[profile.release]
panic = 'abort'